// src/pages/Messaging.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref, watch, nextTick } from 'vue'
import { supabase } from '@/integrations/supabase/client'
import Sidebar from '@/components/Sidebar.vue'
import Button from '@/components/ui/Button.vue'
import Input from '@/components/ui/Input.vue'
import { showError } from '@/utils/toast'
import { Send } from 'lucide-vue-next'
import { cn } from '@/lib/utils'
import type { User } from '@supabase/supabase-js'

interface Message {
  id: string
  user_id: string
  content: string
  created_at: string
}

const messages = ref<Message[]>([])
const loading = ref(true)
const user = ref<User | null>(null)
const newMessage = ref('')
const messagesEnd = ref<HTMLElement | null>(null)

let channel: ReturnType<typeof supabase.channel> | null = null

const fetchMessages = async () => {
  loading.value = true
  const { data, error } = await supabase
    .from('messages')
    .select('id, user_id, content, created_at')
    .order('created_at', { ascending: true })
    .limit(50)

  if (error) {
    console.error('Error fetching messages:', error)
    showError('Failed to load messages.')
  } else if (data) {
    messages.value = data
  }
  loading.value = false
}

onMounted(async () => {
  const { data: { user: currentUser } } = await supabase.auth.getUser()
  user.value = currentUser

  if (currentUser) {
    await fetchMessages()

    // Set up real-time subscription
    channel = supabase
      .channel('public:messages')
      .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'messages' }, async (payload) => {
        const { data, error } = await supabase
          .from('messages')
          .select('id, user_id, content, created_at')
          .eq('id', payload.new.id)
          .single()

        if (!error && data) {
          messages.value = [...messages.value, data]
        }
      })
      .subscribe()
  } else {
    loading.value = false
  }
})

onUnmounted(() => {
  channel?.unsubscribe()
})

// Auto-scroll when messages change
watch(messages, async () => {
  await nextTick()
  messagesEnd.value?.scrollIntoView({ behavior: 'smooth' })
})

const handleSendMessage = async () => {
  if (!user.value || !newMessage.value.trim()) {
    return
  }

  const { error } = await supabase
    .from('messages')
    .insert([{
      user_id: user.value.id,
      content: newMessage.value,
    }])

  if (error) {
    console.error('Error sending message:', error)
    showError('Failed to send message.')
  } else {
    newMessage.value = ''
  }
}

const isCurrentUser = (messageUserId: string) => {
  return user.value && messageUserId === user.value.id
}
</script>

<template>
  <div v-if="loading" class="flex items-center justify-center min-h-screen">
    Loading messages...
  </div>
  <div v-else-if="!user" class="flex items-center justify-center min-h-screen">
    Please log in to view messages.
  </div>
  <div v-else class="flex min-h-screen bg-gray-100">
    <Sidebar />
    
    <div class="flex-1 p-8 flex flex-col h-screen">
      <div class="text-center mb-8">
        <h1 class="text-4xl font-bold mb-2">Public Chat</h1>
        <p class="text-xl text-gray-600 mt-4">Chat with other logged-in users.</p>
      </div>

      <!-- Message Display Area -->
      <div class="flex-1 overflow-y-auto p-4 bg-white rounded shadow-md mb-4 space-y-4">
        <p v-if="messages.length === 0" class="text-center text-gray-600">
          No messages yet. Send one below!
        </p>
        <div
          v-for="message in messages"
          :key="message.id"
          :class="cn(
            'flex items-start space-x-3',
            isCurrentUser(message.user_id) ? 'justify-end' : 'justify-start'
          )"
        >
          <div
            :class="cn(
              'max-w-xs p-3 rounded-lg',
              isCurrentUser(message.user_id)
                ? 'bg-blue-500 text-white'
                : 'bg-gray-300 text-gray-800'
            )"
          >
            <p class="text-sm font-semibold mb-1">
              User ID: {{ message.user_id.slice(0, 8) }}...
            </p>
            <p>{{ message.content }}</p>
            <p class="text-xs mt-1 opacity-75">
              {{ new Date(message.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) }}
            </p>
          </div>
        </div>
        <div ref="messagesEnd"></div>
      </div>

      <!-- New Message Form -->
      <div class="bg-white p-4 rounded shadow-md">
        <form @submit.prevent="handleSendMessage" class="flex space-x-2">
          <Input
            v-model="newMessage"
            placeholder="Type your message..."
            class="flex-1"
          />
          <Button type="submit" size="icon">
            <Send class="h-4 w-4" />
          </Button>
        </form>
      </div>
    </div>
  </div>
</template>

// src/pages/Messaging.tsx
import { useState, useEffect, useRef } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Button, buttonVariants } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent } from '@/components/ui/card';
import { showSuccess, showError } from '@/utils/toast';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import * as z from 'zod';
import { Form, FormControl, FormField, FormItem, FormMessage } from "@/components/ui/form";
import { Link } from 'react-router-dom';
import { cn } from '@/lib/utils';
import { Send } from 'lucide-react'; // Import Send icon

// Define the schema for the new message form
const messageFormSchema = z.object({
  content: z.string().min(1, { message: "Message cannot be empty." }),
});

type MessageFormValues = z.infer<typeof messageFormSchema>;

interface Message {
  id: string;
  user_id: string;
  content: string;
  created_at: string;
  // profiles?: { first_name: string | null; last_name: string | null } | null; // Removed for now
}

const Messaging = () => {
  const [messages, setMessages] = useState<Message[]>([]);
  const [loading, setLoading] = useState(true);
  const [user, setUser] = useState<any>(null);
  const messagesEndRef = useRef<HTMLDivElement>(null); // Ref for auto-scrolling

  const form = useForm<MessageFormValues>({
    resolver: zodResolver(messageFormSchema),
    defaultValues: {
      content: '',
    },
  });

  // Function to fetch messages
  const fetchMessages = async () => {
    setLoading(true);
    // Fetch only message fields for now
    const { data, error } = await supabase
      .from('messages')
      .select('id, user_id, content, created_at') // Select specific fields
      .order('created_at', { ascending: true }) // Order by timestamp
      .limit(50); // Limit the number of messages

    if (error) {
      console.error('Error fetching messages:', error);
      showError('Failed to load messages.');
    } else if (data) {
      console.log('Fetched messages:', data); // Log fetched data
      setMessages(data);
    }
    setLoading(false);
  };

  // Fetch user and initial messages on component mount
  useEffect(() => {
    const fetchUser = async () => {
      const { data: { user } } = await supabase.auth.getUser();
      setUser(user);
      if (user) {
        fetchMessages();
      } else {
        setLoading(false); // Stop loading if no user
      }
    };

    fetchUser();

    // Set up real-time subscription for new messages
    const subscription = supabase
      .channel('public:messages') // Channel name
      .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'messages' }, async (payload) => {
        console.log('New message received!', payload);
        // Fetch the new message without profile data for now
        const { data, error } = await supabase
          .from('messages')
          .select('id, user_id, content, created_at') // Select specific fields
          .eq('id', payload.new.id)
          .single();

        if (error) {
          console.error('Error fetching new message data:', error);
        } else if (data) {
          console.log('Fetched new message:', data); // Log new message data
          setMessages((prevMessages) => [...prevMessages, data]);
        }
      })
      .subscribe();

    // Clean up subscription on component unmount
    return () => {
      subscription.unsubscribe();
    };

  }, []); // Empty dependency array means this runs once on mount

  // Auto-scroll to the latest message when messages change
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);


  // Handle new message submission
  async function onSubmit(values: MessageFormValues) {
    if (!user) {
      showError('You must be logged in to send messages.');
      return;
    }

    const { error } = await supabase
      .from('messages')
      .insert([
        {
          user_id: user.id,
          content: values.content,
        },
      ]);

    if (error) {
      console.error('Error sending message:', error);
      showError('Failed to send message.');
    } else {
      // Message sent successfully, real-time subscription will add it to the list
      form.reset(); // Clear the form
    }
  }

  if (loading) {
    return <div className="flex items-center justify-center min-h-screen">Loading messages...</div>;
  }

  if (!user) {
     return <div className="flex items-center justify-center min-h-screen">Please log in to view messages.</div>;
  }

  // Determine if the current user sent the message
  const isCurrentUser = (messageUserId: string) => user && messageUserId === user.id;

  return (
    <div className="flex min-h-screen bg-gray-100">
      {/* Sidebar */}
      <div className="w-64 bg-white shadow-md p-4 flex flex-col">
        <h3 className="text-lg font-semibold mb-4">Mini Apps</h3>
        <ul className="flex-grow space-y-2">
          <li>
            <Link
              to="/dashboard"
              className={cn(
                buttonVariants({ variant: "ghost" }),
                "w-full justify-start"
              )}
            >
              Dashboard
            </Link>
          </li>
          <li>
            <Link
              to="/notes"
              className={cn(
                buttonVariants({ variant: "ghost" }),
                "w-full justify-start"
              )}
            >
              Notes
            </Link>
          </li>
           <li>
            <Link
              to="/gallery"
              className={cn(
                buttonVariants({ variant: "ghost" }),
                "w-full justify-start"
              )}
            >
              Gallery
            </Link>
          </li>
           <li>
            <Link
              to="/messaging"
              className={cn(
                buttonVariants({ variant: "ghost" }),
                "w-full justify-start"
              )}
            >
              Messaging
            </Link>
          </li>
          {/* Add links for future mini-apps here */}
        </ul>
        {/* Logout button can be added here or in a shared layout */}
      </div>

      {/* Main Content Area */}
      <div className="flex-1 p-8 flex flex-col h-screen"> {/* Use flex-col and h-screen for layout */}
        <div className="text-center mb-8">
          <h1 className="text-4xl font-bold mb-2">Public Chat</h1>
          <p className="text-xl text-gray-600 mt-4">Chat with other logged-in users.</p>
        </div>

        {/* Message Display Area */}
        <div className="flex-1 overflow-y-auto p-4 bg-white rounded shadow-md mb-4 space-y-4">
          {messages.length === 0 ? (
            <p className="text-center text-gray-600">No messages yet. Send one below!</p>
          ) : (
            messages.map((message) => (
              <div
                key={message.id}
                className={cn(
                  "flex items-start space-x-3",
                  isCurrentUser(message.user_id) ? "justify-end" : "justify-start" // Align right for current user
                )}
              >
                {/* Could add avatar here */}
                <div
                  className={cn(
                    "max-w-xs p-3 rounded-lg", // Basic bubble styling
                    isCurrentUser(message.user_id)
                      ? "bg-blue-500 text-white" // Blue background for current user
                      : "bg-gray-300 text-gray-800" // Gray background for others
                  )}
                >
                  {/* Display user_id for now */}
                  <p className="text-sm font-semibold mb-1">
                    User ID: {message.user_id}
                  </p>
                  <p>{message.content}</p>
                  <p className="text-xs mt-1 opacity-75"> {/* Dim timestamp slightly */}
                    {new Date(message.created_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}
                  </p>
                </div>
              </div>
            ))
          )}
          <div ref={messagesEndRef} /> {/* Empty div for scrolling */}
        </div>

        {/* New Message Form */}
        <div className="bg-white p-4 rounded shadow-md">
          <Form {...form}>
            <form onSubmit={form.handleSubmit(onSubmit)} className="flex space-x-2">
              <FormField
                control={form.control}
                name="content"
                render={({ field }) => (
                  <FormItem className="flex-1">
                    <FormControl>
                      <Input placeholder="Type your message..." {...field} />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
              <Button type="submit" size="icon">
                <Send className="h-4 w-4" />
              </Button>
            </form>
          </Form>
        </div>
      </div>
    </div>
  );
};

export default Messaging;
